name: 'Devolutions Server Get SecretEntry'

on:
  workflow_dispatch:

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Get DVLS secret
        uses: adbertram/devolutions-server-get-entry@main
        with:
          server_url: 'https://52.249.182.1/dvls1'
          app_key: '76c84f6c-92c3-4e9a-ad4d-c23d9428b7b0'
          app_secret: 'uCU2O2dA5YvveHX7cXyFgBpVxdoRYUPioeuFfOkosQeSxesAX4Ri7qZPUUkJ1YxL'
          vault_name: 'DevOpsSecrets'
          entry_name: 'azure-acr'
          output_variable: 'MY_SECRET_VALUE'

      - name: Show secret with string manipulation
        run: |
          secret="${{ env.MY_SECRET_VALUE }}"
          echo "First character: ${secret:0:1}"
          echo "Rest of secret: ${secret:1}"
